---
application:
  name: "nexushub-workshop"
  project: "nexusApps"
  organization: "QoveryCommunity"
routers:
- name: "main-nexushub-workshop"
  routes:
  - application_name: "nexushub-workshop"
    paths:
    - "/*"
