application:
  name: nexushub-workshop
  project: nexusApps
  publicly_accessible: true
  port: 3001
  dockerfile: nexushub-workshop/Dockerfile
routers:
- name: main
  routes:
  - application_name: nexushub-workshop
    paths:
    - /nexushub-workshop/
